export const USER_TASKS = '/api-lass/userTasks'
export const USER_TASK = '/api-lass/userTasks/task'
export const SUPS_TASKS = '/api-lass/supsTasks/'
export const SUPS_TASK = '/api-lass/supsTasks/task'
export const ACCEPT_TASK = '/api-lass/supsTasks/accept'
export const MILESTONE_TASK = '/api-lass/task'
export const READING_PAPERS = '/api-lass/userTasks/paper'
export const READING_MILESTONE_PAPERS = '/api-lass/task/paper'
