export const GET_MY_LABS = '/api-lass/labs/my'
export const CREATE_LAB = '/api-lass/labs'
export const GET_LABS_LIST = '/api-lass/labs'
export const ENROLL_USER = '/api-lass/labs/enroll'
export const SPECIFIC_LAB = '/api-lass/labs'