export const SUPS_RECENT_FILES = '/api-lass/supervisor/recent'
export const ADD_PERMISSIONS = '/api-lass/supervisor/permission'
export const CREATE_SUPS = '/api-lass/supervisor'
export const ADD_SAND = '/api-lass/supervisor/sand'
export const ADD_SMARTIES = '/api-lass/supervisor/smarties'
export const UPDATE_SUPS_PROFILE_PICTURE = '/api-lass/supervisor/update-profile-picture'
